config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :taxonomies do
      resources :taxons do
        resources :bullets
      end
    end
  end
end

#                        admin_taxon_bullets GET    /admin/taxons/:taxon_id/bullets(.:format)                            spree/admin/bullets#index
#                                            POST   /admin/taxons/:taxon_id/bullets(.:format)                            spree/admin/bullets#create
#                     new_admin_taxon_bullet GET    /admin/taxons/:taxon_id/bullets/new(.:format)                        spree/admin/bullets#new
#                    edit_admin_taxon_bullet GET    /admin/taxons/:taxon_id/bullets/:id/edit(.:format)                   spree/admin/bullets#edit
#                         admin_taxon_bullet GET    /admin/taxons/:taxon_id/bullets/:id(.:format)                        spree/admin/bullets#show
#                                            PUT    /admin/taxons/:taxon_id/bullets/:id(.:format)                        spree/admin/bullets#update
#                                            DELETE /admin/taxons/:taxon_id/bullets/:id(.:format)                        spree/admin/bullets#destroy
     

app/models/spree/bullet.rb
class Spree::Bullet < ActiveRecord::Base
  belongs_to :taxon
  has_many :products
      
  attr_accessible :taxon, :taxon_id, :image_code, :description, :line_number, :is_active
    
  validates :description, :presence => true

  scope :active, where(:is_active => true)
  scope :sorted, order("line_number asc")
  scope :sorted_by_image_code, order("image_code asc, line_number asc")
  scope :image_code, lambda{|image_code| where(:image_code => image_code)}
  
end

app/models/spree/taxon_decorator.rb
Spree::Taxon.class_eval do
  has_many :bullets

end

app/controllers/spree/admin/bullets_controller.rb
class Spree::Admin::BulletsController < Spree::Admin::BaseController
  respond_to :html

  before_filter :load_parent
  
  def index
    @bullets = Spree::Bullet.sorted_by_image_code.where(:taxon_id => @taxon.id)
    respond_with(:admin, @taxonomy, @taxon) 
  end
  
  def new
    @bullet = Spree::Bullet.new(:taxon_id => @taxon.id, :is_active => true)
  end
  
  def create
    @bullet = Spree::Bullet.new(params[:bullet].merge(:taxon_id => @taxon.id))
    
    if @bullet.save
      flash[:notice] = t(:successfully_created_bullet)
      redirect_to admin_taxonomy_taxon_bullets_url(@taxonomy, @taxon)
    else
      respond_with(@bullet)
      flash[:error] = t(:error_creating)
    end
    
  end
  
  def update
    if @bullet.update_attributes(params[:bullet])
      flash.notice = t(:successfully_updated_bullet)
      redirect_to admin_taxonomy_taxon_bullets_url(@taxonomy, @taxon)
    else
      respond_with(@bullet)
    end
  end

    
  def destroy
    if @bullet.destroy
      flash[:notice] = t(:successfully_removed_bullet)
    else
      flash[:error] = t(:error_deleting)
    end
    redirect_to admin_taxonomy_taxon_bullets_url(@taxonomy, @taxon)
  end
  
  private
  def load_parent
    @taxonomy = Spree::Taxonomy.find(params[:taxonomy_id])
    @taxon = @taxonomy.taxons.find(params[:taxon_id])
    @bullet = Spree::Bullet.find(params[:id]) if params[:id]
  end
end

app/views/spree/admin/bullets/_form.html.erb
<%= f.field_container :description do %>
  <%= f.label :description, t(:description) %><br />
  <%= f.text_area :description, {:cols => 60, :rows => 4, :class => 'fullwidth'}  %>
<% end %>

<%= f.field_container :image_code do %>
  <%= f.label :image_code, t(:image_code) %><br />
  <%= f.text_field :image_code %>
  <p>
    Hint: This could be a property of the product. This way you can 'tie' different bullets to the products based on the image code. 
    For example in a category all the products with the same image code will have the same bullets.
    You have to create the image_code propery by your own. And use the right partial in the store (it is included in the extension)
  </p>
<% end %>

<%= f.field_container :line_number do %>
  <%= f.label :line_number, t(:line_number) %><br />
  <%= f.text_field :line_number %>
<% end %>

<%= f.field_container :is_active do %>
  <%= f.label :is_active, t(:active), :for=> 'bullet_is_active_1' %><%= f.radio_button(:is_active, "1") %>
  <%= f.label :is_active, t(:not_active), :for=> 'bullet_is_active_0' %><%= f.radio_button(:is_active, "0") %>
<% end %>

app/views/spree/admin/bullets/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<h1>Editing Bullet</h1>

<%= render 'spree/shared/error_messages', :target => @bullet %>

<%= form_for  [:admin, @taxonomy, @taxon, @bullet], :html => { :multipart => true } do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <p class="form-buttons" data-hook="buttons"><%= button t(:save) %></p>
<% end %>

app/views/spree/admin/bullets/index.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<div class="toolbar" data-hook="toolbar">
  <ul class="actions">
    <li>
      <p><%= button_link_to t(:'new'), new_admin_taxonomy_taxon_bullet_url( @taxonomy, @taxon), :icon => 'add' %></p>
    </li>
  </ul>
  <br class="clear" />
</div>

<h1>Bullets</h1>
<h2><%= @taxonomy.name %> / <%= @taxon.name %></h2>

<table class="index" id="listing_bullets" data-hook="table-bullets">
  <thead>
    <tr data-hook="admin_bullets_index_headers">
      <th><%= t(:value) %></th>
      <th><%= t(:image_code) %></th>
      <th><%= t(:sort) %></th>
      <th><%= t(:active) %></th>
      <th data-hook="admin_bullets_index_header_actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @bullets.each do |bullet|%>
      <tr data-hook="admin_bullets_index_rows">
        <td><%= link_to truncate(bullet.description, :length => 100), edit_admin_taxonomy_taxon_bullet_url(@taxonomy, @taxon, bullet), :class => 'edit' %></td>
        <td><%= bullet.image_code %>
        <td><%= bullet.line_number %>
        <td><%= bullet.is_active == 1 ? image_tag('admin/icons/16x16/4.png') : image_tag('admin/icons/16x16/2.png') %>
        <td data-hook="admin_bullets_index_row_actions">
          <%= link_to t('edit'), edit_admin_taxonomy_taxon_bullet_url(@taxonomy, @taxon, bullet), :class => 'edit' %> &nbsp;
          <%= link_to t('delete'), [:admin, @taxonomy, @taxon, bullet], :confirm => "Are you sure?", :method=>:delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to t(:'Back'), edit_admin_taxonomy_url( @taxonomy ) %></p>

app/views/spree/admin/bullets/new.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<h1>New Bullet</h1>
<%= render 'spree/shared/error_messages', :target => @bullet %>

<%= form_for [:admin, @taxonomy, @taxon, @bullet], :html => { :multipart => true } do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <p class="form-buttons" data-hook="buttons"><%= button t(:create) %></p>
<% end %>

app/views/spree/admin/taxons/_to_bullets_index.html.erb
<%= link_to t(:attached_bullets), admin_taxonomy_taxon_bullets_path(@taxonomy, @taxon) %>

app/views/spree/products/_bullets.html.erb
<% 
show_bullets_for_taxon = @product.taxons.first

bullets = show_bullets_for_taxon.bullets.active.sorted

unless !(@product or bullets.empty?) %>
  <section id="bullets">
    <ul>
      <% 
      bullets.each do |bullet| %>
        <%= content_tag :li, bullet.description %>
      <% end %>
    </ul>
  </section>
<% end %> 

app/views/spree/products/_custom_bullets.html.erb
<% 
show_bullets_for_taxon = @product.taxons.first

image_code_property_id = @product.product_properties.where(:property_id => Gator::Application::PRODUCT_PROPERTIES[:image_code] ).first.value

bullets = show_bullets_for_taxon.bullets.image_code(image_code_property_id).active.sorted

unless !(@product or bullets.empty?) %>
  <section id="bullets">
    <ul>
      <% 
      bullets.each do |bullet| %>
        <%= content_tag :li, bullet.description %>
      <% end %>
    </ul>
  </section>
<% end %> 